<?xml version="1.0" encoding="utf-8"?>
<TestRecord xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Results>
    <UnitTestResult>
      <TestDate>2011-11-25T00:05:58</TestDate>
      <Status>Failure</Status>
      <TotalFailures>0</TotalFailures>
      <TotalSuccess>0</TotalSuccess>
      <TotalIgnored>0</TotalIgnored>
      <Time />
      <Message>Object reference not set to an instance of an object</Message>
      <StackTrace>  at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke (System.Runtime.Remoting.Proxies.RealProxy rp, IMessage msg, System.Exception&amp; exc, System.Object[]&amp; out_args) [0x00000] in &lt;filename unknown&gt;:0 </StackTrace>
    </UnitTestResult>
    <UnitTestResult>
      <TestDate>2011-11-25T00:06:12</TestDate>
      <Status>Failure</Status>
      <TotalFailures>0</TotalFailures>
      <TotalSuccess>0</TotalSuccess>
      <TotalIgnored>0</TotalIgnored>
      <Time />
      <Message>Object reference not set to an instance of an object</Message>
      <StackTrace>  at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke (System.Runtime.Remoting.Proxies.RealProxy rp, IMessage msg, System.Exception&amp; exc, System.Object[]&amp; out_args) [0x00000] in &lt;filename unknown&gt;:0 </StackTrace>
    </UnitTestResult>
  </Results>
</TestRecord>